### ISSUE TITLE
Making heading more precise?

### ISSUE THREAD

**Issue by Ziqi-Yang** [uben0/tree-sitter-typst#1]
Currently, the parser see `=`, `==` and `===` etc. as the same `heading`
What about making heading more precise? Like `(heading "=" text)`,  `(heading "==" text)` so user can set different style for each level of headings

**Comment by uben0** [comment]
Absolutelly!

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Ziqi-Yang** [comment]
Also it would be nicer if the sub-tree of `item` is like `(item "-" (text))`,  so users can highlight only the item indicator "-".

**Comment by uben0** [comment]
Now the tree have distinct `(heading "=" ...)` and `(heading "==" ...)` and etc. But I don't know if all editors can highlight the heading content differently based on the different marker. Different `heading` may be required like `(heading1 ...)`, `(heading2 ...)`. But I am looking after to keep the grammar as simple as possible and also not to increase its size for performance.

**Comment by Ziqi-Yang** [comment]
This two queries are not the same of course:
```
(heading "=" (text)) @markup.heading1
(heading "==" (text)) @markup.heading2
```
and I think to identify different queries should be a basic capability of the tree sitter integration of an editor? An editor cannot distinguish two queries like this is supposed to improve its tree sitter integration. As far as I know, NeoVim, Helix and Emacs uses query to do syntax highlighting and this shouldn't be any problem. IDW if there are some editors do tree sitter syntax highlighting using only the node type or some thing else, but I think it would be impossible.
