### ISSUE TITLE
Adding heading level to the queries

### ISSUE THREAD

**Issue by Idobenhamo** [uben0/tree-sitter-typst#11]
First of all thank you for your amazing work!!
It would be great if heading level recognition was added. I tried to look at helix queries folder and saw how the markdown queries are defined (if it can help)
![Screenshot 2023-11-08 085434](https://github.com/uben0/tree-sitter-typst/assets/135357971/bde1bb9c-1916-4363-8025-10cf7bd7765e)

![Screenshot 2023-11-08 085444](https://github.com/uben0/tree-sitter-typst/assets/135357971/359bd29e-161b-4837-a219-3ea5761f1411)

**Comment by uben0** [comment]
Could you try with the new modifications ?
You have to update the grammar and the `hightlights.scm` file.

**Comment by Idobenhamo** [comment]
thanks you! its working now
