### ISSUE TITLE
Dimmed list items in Helix

### ISSUE THREAD

**Issue by Iorvethe** [uben0/tree-sitter-typst#2]
Hi!

Text in list items appears to be miscolored in Helix. Compared to markdown:

| Markdown | Typst |
|- | - |
| ![image](https://github.com/uben0/tree-sitter-typst/assets/58810330/c80c450f-f2f5-460b-9c6d-6a831d425bb1) | ![image](https://github.com/uben0/tree-sitter-typst/assets/58810330/8c243a18-1f5b-4f90-a040-b60332b5d236) |

**Comment by uben0** [comment]
Indeed, I know what the problem is.  At the time of writting, I didn't know if the scope `markup.item` was meant for the dash or for the content. In this grammar it applies to whole item's content. I'll change this.

**Comment by uben0** [comment]
I believe I fixed. Could you check if it works correctly now?

**Comment by Iorvethe** [comment]
Great, just tested it, and it works perfectly now. Thanks for your quick reply and fix!
