### ISSUE TITLE
If Else incremental parsing issue

### ISSUE THREAD

**Issue by Ziqi-Yang** [uben0/tree-sitter-typst#23]
Using latest parser: [2d68228e](https://github.com/uben0/tree-sitter-typst/commit/2d68228e8af537fccd02b10c9b37b353238cfa5e)  

---

```typst
#if 1 < 2 [
  show
] else [
  hide
]
```
The tree structure can be parsed correctly at the document loading (I think the parser will parse the whole documentation).  
When I'm editing this code, i.e.
```typst
if 1 < 2 [
  show
] // <- cursor here
```
when my cursor is directly after `]` character, and I type `else`(i.e. `]else`) the tree structure also parsed correctly. Then  if I add a space before `else`, the parsed tree structure is also correct. However, if I type a space after `]`, then type `else`( i.e. `] else`), the tree structure is wrong. The produced tree structure is
```
(source_file #
 (branch if
  condition: (cmp (number) < (number))
  (content [ (text) ]))
 end (text) (text) (parbreak) (text) (parbreak))
```
I think it may be a problem related to this parse itself (also maybe related to Emacs editor`), so I post it here.

**Comment by uben0** [comment]
Yes, I can reproduce the bug on Helix too. I type `#if true [] else []` and `else []` is not recognized. If a space is inserted later just after the `]`, then it recognizes the `else []`.

I might have introduce the bug in the latest commit, when fixing issue #22, by considering line breaks as hard code end.

But what is strange, is the sensitivity to context (order of characters insertion). I'm almost sure the only way to have context sensitive issues is to have a wrong context saving/loading (serialization/deserialization).

**Comment by uben0** [comment]
I don't know if I have a very convincing *déjà vue* effect. But I'm almost sure I already encountered this bug before and I already fixed it. I just reintroduced it.

And the bug cannot be reproduced in a *tree sitter* test:

```typst
#if false [] else []
```
```scm
(source_file
  (branch
    (bool)
    (content)
    (content)))
```

**Comment by uben0** [comment]
I know what's going on...

- `_`: code
- `.`: markup
- `+`: just inserted

```
____________.
#if false []
```
```
____________.+++++++.
#if false [] else []
```

When characters are inserted, *tree sitter* only updates the nodes spanning over the modified content. In this situation, it tries to parse `else []` as markup and interprets it as text:

```
____________.........
#if false [] else []
```

Maybe it's because the `space` token is emitted after the `code_end` token. I'll have a look.

**Comment by uben0** [comment]
Let me correct myself:

```
____________....
#if false [] els
```
```
____________....+
#if false [] else
```

**Comment by uben0** [comment]
I believe I fixed the issue 6241b9461f5c5d3d47277618d7655152da70af9f 🥳

I can no longer reproduce the bug.

Could you test if it works correctly?

Explanation: I added an explicit optional space before the `else` to force the space token to be part of the `branch` node.


PS: Not so fast... I forgot about comments 🫣

**Comment by uben0** [comment]
There it is 3a6c81bb56082604f5e63834cb2f946beeda1e76

**Comment by Ziqi-Yang** [comment]
After testing,  I think the problem is fixed. Sorry for the late reply, I forgot it.
