### ISSUE TITLE
`bindings/rust/lib.rs` missing from repo

### ISSUE THREAD

**Issue by ju6ge** [uben0/tree-sitter-typst#24]
Hey I am trying to use this as a crate together with the `tree-sitter` carte. Sadly it does not compile because the `lib` path specified in the Cargo.toml does not exist in this repository.

Is there a way to generate it?

**Comment by uben0** [comment]
I added it to the tracked files. f70f88b2a33e7d2e9fbfef5cecb8579173208985 contains it. Could you try again and tell me if it works now?

This file is automatically generated but I don't remember which *tree sitter* command does.

**Comment by ju6ge** [comment]
yes I can confirm it works now :+1:
