### ISSUE TITLE
Context expressions

### ISSUE THREAD

**Issue by tingerrr** [uben0/tree-sitter-typst#27]
It would be great if we could add support for parsing context expressions such that this grammar is 0.11.0 compliant.

From an uneducated look, it seems that context expressions behave the same in terms of parsing as an [include expression, with slightly different precedence](https://github.com/typst/typst/blob/41db766b83bad4c4671423c03c5e54f308032e7b/crates/typst-syntax/src/parser.rs#L910-L916).

**Comment by uben0** [comment]
I added the `context` operator. I only wrote a single test for it at the moment, but I'll need more test.

About the 0.11 update, I don't know if I understand 100% all the syntax modifications. I'll open an issue for 0.11 update.
