### ISSUE TITLE
fprintf and exit unsupported under wasm

### ISSUE THREAD

**Issue by WeetHet** [uben0/tree-sitter-typst#29]
When trying to use this grammar with wasm, I stumbled into the two following problems:
- `Failed to instantiate wasm module: invalid import 'fwrite'`
- `Failed to instantiate wasm module: invalid import 'exit'`

This can be solved by commenting all `fprintf`-s and `exit`-s or hiding them behind a guard:
```c++
#if defined(__EMSCRIPTEN__) || defined(__wasm__) || defined(__wasm32__) || defined(__wasm64__)
// use wasm stuff
#else
fprintf(stderr, "vec_u32_deserialize: malloc failed\n");
exit(EXIT_FAILURE);
#endif
```

I would really appreciate you fixing this, as I use zed editor which, in term, uses grammars compiled to wasm

**Comment by uben0** [comment]
It's done. Could you tell me if it works now?

I did not check for particular targets, but directly used a macro definition which is commented when not in debug mode.

**Comment by WeetHet** [comment]
It works, cool, thanks!
