### ISSUE TITLE
Math shorthand `==>` for `arrow.r.double.long` is recognized as `=` followed by `=>`

### ISSUE THREAD

**Issue by lntricate1** [uben0/tree-sitter-typst#30]
Expected behavior: `==>` is recognized as a single shorthand.

Actual behavior: `==>` is recognized as the symbol `"="` followed by the shorthand `=>`.

**Comment by uben0** [comment]
I fixed it in 4610172f312e8ce5184e6882be5ad1a1cd800fbe

Could you try if it works correctly on your side?
