### ISSUE TITLE
Nested code blocks

### ISSUE THREAD

**Issue by tingerrr** [uben0/tree-sitter-typst#31]
It seems at the current moment nested code blocks are unsupported, the following snippet compiles fine, but highlights incorrectly:

![image](https://github.com/uben0/tree-sitter-typst/assets/137803093/d7bbbd8e-10c2-43a1-9aa5-3c8a352e07f5)

I am using 13863ddcbaa7b68ee6221cea2e3143415e64aea4 on helix, and by the looks of it no later commit introduces support for this.

A minimal example which reproduces the issue:
``````typst
````typst
#not-highlighted()
```
#highlighted()
```
````
``````

The rules for this are simple, the closing delimiter's backtick count must match the opening delimiter's backtick count.

**Comment by uben0** [comment]
I totally missed that the number of backticks was arbitrary (and I was thinking to myself "it would be cool if they added the feature" XD)

I'll work on it.

**Comment by uben0** [comment]
fixed ! b19e64087a426fe059fc6103ff0766c607f41888
before closing the issue, I want confirmation it works on someone else machine.

**Comment by tingerrr** [comment]
![image](https://github.com/uben0/tree-sitter-typst/assets/137803093/67d7625d-fcd7-4e12-ae4e-2708cd0e43b3)

Appears to work correctly!
