### ISSUE TITLE
Add heading sections to grammar

### ISSUE THREAD

**Issue by gzagatti** [uben0/tree-sitter-typst#6]
Thanks for putting this parser together. I have started using it with neovim.

It would be useful if the grammar defined sections which would allow for easily folding in neovim using tree-sitter queries. For instance, all the items below heading 1 would be a section, all items below heading 2 would be a sub-section, etc. At the moment most of the lines occupy the same hierarchy so we cannot define folds except for code blocks, groups and math.

Here's an example of the folded text.

![image](https://github.com/uben0/tree-sitter-typst/assets/11043156/2f0475b8-e3d6-440b-961a-4844017cb8f6)

Do you think it would be easy to add sections? I'm not super familiar with how the treesitter source code works.

**Comment by uben0** [comment]
I haven't look yet at what the `queries.scm` does. I'll do it. I don't know if this is difficult. I don't know if the fold have to apply on child nodes. Because, if it is the case, the grammar has to be modified in order to have heading has parent node for content following them.

Do you have an example of this in action with, for instance, Markdown? I'll have a look at how other languages handle that.

**Comment by uben0** [comment]
I'll have a look on how to implement that. No idea if this is tricky or not.

**Comment by gzagatti** [comment]
Thanks for your response. I think you would need to modify the grammar.

A good place to start is looking at how they do in markdown starting with this [line](https://github.com/MDeiml/tree-sitter-markdown/blob/aaf76797aa8ecd9a5e78e0ec3681941de6c945ee/tree-sitter-markdown/grammar.js#L38). For instance section 1 is defined as a sequence with the following elements:

```js
_section1: $ => prec.right(seq(
    alias($._atx_heading1, $.atx_heading),
    repeat(choice(
        alias(choice($._section6, $._section5, $._section4, $._section3, $._section2), $.section),
        $._block_not_section
    ))
)),
```

**Comment by uben0** [comment]
```typ
= Hello
World
```

What is the desired tree?

```scm
(heading)
(section
    (text))
```
Or
```scm
(section
    (heading)
    (text))
```

What makes more sens?

**Comment by uben0** [comment]
Functionality added! d7e552f4a8db931b9205480e3de65885719b2928 🎉

Could you test it and give a feed back?

By the way, I went for the separate tree:
```scm
(heading)
(section
    (text))
```

**Comment by gzagatti** [comment]
@uben0 sorry for the delay in coming back to you, I was away during the holiday season.  Thanks for adding the functionality. In terms of folding it works perfectly. 

But I would suggest going for 

```
(section
    (heading)
    (text))
```

My reasoning is that a section includes the heading. This follows from [Typst documentation](https://typst.app/docs/reference/model/heading/):

> With headings, you can structure your document into sections. Each heading has a level, which starts at one and is unbounded upwards. This level indicates the logical role of the following content (section, subsection, etc.) A top-level heading indicates a top-level section of the document (not the document's title).

Also for consistency sake, the markdown parser includes the heading in the section.

Apart from folding, you might also want to use treesitter queries to select the whole section. So if you keep the heading outside of the section, it will be more difficult to create such queries. For instance, I have a shortcut in vim that selects the whole section with `gnn` which does not work with the current setup.

An alternative that incorporate both ideas would be something like:

```
(section
    (heading)
    (content
      (text)))
```

That way all the contents of the section are nested inside `content` and it is easy to select the whole section or only the content.

**Comment by uben0** [comment]
You are right

I modified the grammar -> f3b362d58914fe578658bcf303ace1569060f3bb

I went for the following hierarchy:

```scm
(section
    (heading)
    (content
        (text)))
```

**Comment by gzagatti** [comment]
That's perfect! It works very well. I close the issue as it is resolved. Thanks for fixing this issue!
