### ISSUE TITLE
Add parsing rule for hexadecimal values

### ISSUE THREAD

**Issue by Nagefire** [uben0/tree-sitter-typst#9]
Typst allows for C-style hexadecimal strings (0xff) as unsigned integers in code contexts. Currently, the grammar shows (ERROR) for these values

**Comment by uben0** [comment]
The grammar does support this notation, maybe the bug is due to context. Can you try to isolate the bug, like find the minimal code to produce the error?

**Comment by Nagefire** [comment]
Found the bug, my session was pointing to a different pointer
